## Importing Dataset


---

Dataset contains various information about apartment from Belgium. we should find out what is the factor for Apartment price and some descriptive insight from this data set.

</br>Column details:</br>
* locality str: Postal code of city.
* type_of_property str: House or Apartment.
* subtype_of_property str: Bungalow, Villa, ...
* price float: Price (â‚¬) of the property.
* type_of_sale str The type of sale.
* number_of_rooms int: The number of rooms of the property.
* house_area int: The area (m2) of the house (floors).
* fully_equipped_kitchen bool: If the house has a fully equipped kitchen or not.
* furnished bool: If the house is furnished or not.
* open_firebool: If there's an open fire or not.
* terrace bool: If there's a terrace or not.
* terrace_area float: The area (m2) of the terrace.
* garden bool: If there's a garden or not.
* garden_area float: The area (m2) of the garden.
* surface_of_the_land float: The area (m2) of the land.
* surface_of_the_plot_of_land float: The area (m2) of the land's plot.
* number_of_facadess int: The number of facades (0 to 4).
* swimming_pool bool: If there's a swimming pool or not.
* state_of_the_building str: Good, As new, To be renovated, ...
* construction_year int: The property built's year.

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
DATASET_URL = "https://github.com/mdimran1/Dataset/blob/main/real_estate/belgium_apartment.csv?raw=true"

raw_data = pd.read_csv(DATASET_URL)

## Data understanding

In [3]:
# data shape

print(raw_data.shape)

(52077, 20)

In [4]:
raw_data.head(-5)

,locality,type_of_property,subtype_of_property,price,type_of_sale,number_of_rooms,house_area,fully_equipped_kitchen,furnished,open_fire,terrace,terrace_area,garden,garden_area,surface_of_the_land,surface_of_the_plot_of_land,number_of_facades,swimming_pool,state_of_the_building,construction_year
0,1050,house,house,340000,for sale,6.0,203,1,None,0,1,None,0,None,95.0,None,2,0,to be done up,1901
1,1880,house,villa,525000,for sale,6.0,250,1,None,0,1,40,1,430,826.0,None,4,0,as new,1992
2,4900,house,exceptional property,550000,for sale,11.0,475,1,None,0,1,None,1,1400,1543.0,None,4,0,good,1853
3,7912,house,villa,550000,for sale,4.0,325,1,None,0,1,125,1,2333,3570.0,None,4,0,good,1918
4,6032,house,house,550000,for sale,5.0,400,1,None,0,1,80,1,500,616.0,None,3,0,as new,1977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52067,9100,house,house,500000,for sale,4.0,None,0,None,0,0,None,0,None,1288.0,None,4,0,None,None
52068,6700,house,mansion,475000,for sale,9.0,240,0,None,0,0,None,0,None,200.0,None,2,0,None,None
52069,8210,house,farmhouse,486000,for sale,3.0,None,0,None,0,0,None,0,None,0.0,None,4,0,None,1983
52070,8570,house,villa,495000,for sale,3.0,None,0,None,0,1,None,1,None,0.0,None,None,0,as new,None
52071,9880,house,house,489000,for sale,3.0,None,0,None,0,0,None,0,None,800.0,None,4,0,None,None

In [5]:
# data description

raw_data.describe()

,locality,number_of_rooms,fully_equipped_kitchen,open_fire,terrace,garden,surface_of_the_land,swimming_pool
count,52077.000000,52075.000000,52077.000000,52077.000000,52077.000000,52077.000000,29353.000000,52077.000000
mean,5406.222728,2.814575,0.652284,0.046950,0.563569,0.289859,992.812046,0.015957
std,2958.590968,2.202981,0.476250,0.211533,0.495947,0.453701,5026.021908,0.125311
min,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2600.000000,2.000000,0.000000,0.000000,0.000000,0.000000,142.000000,0.000000
50%,5060.000000,3.000000,1.000000,0.000000,1.000000,0.000000,350.000000,0.000000
75%,8430.000000,3.000000,1.000000,0.000000,1.000000,1.000000,810.000000,0.000000
max,9992.000000,204.000000,1.000000,1.000000,1.000000,1.000000,400000.000000,1.000000

In [6]:
# object dtype data description

raw_data.describe(include='object')

,type_of_property,subtype_of_property,price,type_of_sale,house_area,furnished,terrace_area,garden_area,surface_of_the_plot_of_land,number_of_facades,state_of_the_building,construction_year
count,52077,52077,52077,52077,52077,52077,52077,52077,52077,52077,52077,52077
unique,2,24,4220,1,693,1,185,1192,1,5,7,220
top,house,house,199000,for sale,None,None,None,None,None,2,as new,None
freq,29353,22100,683,52077,8632,52077,34559,43624,52077,18219,14826,21369

In [7]:
# Data types 

raw_data.dtypes

locality                         int64
type_of_property                object
subtype_of_property             object
price                           object
type_of_sale                    object
number_of_rooms                float64
house_area                      object
fully_equipped_kitchen           int64
furnished                       object
open_fire                        int64
terrace                          int64
terrace_area                    object
garden                           int64
garden_area                     object
surface_of_the_land            float64
surface_of_the_plot_of_land     object
number_of_facades               object
swimming_pool                    int64
state_of_the_building           object
construction_year               object
dtype: object

In [8]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52077 entries, 0 to 52076
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   locality                     52077 non-null  int64
 1   type_of_property             52077 non-null  object
 2   subtype_of_property          52077 non-null  object
 3   price                        52077 non-null  object
 4   type_of_sale                 52077 non-null  object
 5   number_of_rooms              52075 non-null  float64
 6   house_area                   52077 non-null  object
 7   fully_equipped_kitchen       52077 non-null  int64
 8   furnished                    52077 non-null  object
 9   open_fire                    52077 non-null  int64
 10  terrace                      52077 non-null  int64
 11  terrace_area                 52077 non-null  object
 12  garden                       52077 non-null  int64
 13  garden_area                  52077 non-null  object
 14  surface_of_the_land          29353 non-null  float64
 15  surface_of_the_plot_of_land  52077 non-null  object
 16  number_of_facades            52077 non-null  object
 17  swimming_pool                52077 non-null  int64
 18  state_of_the_building        52077 non-null  object
 19  construction_year            52077 non-null  object
dtypes: float64(2), int64(6), object(12)
memory usage: 7.9+ MB

In [9]:
for column in raw_data.columns:
  no_of_values = raw_data[column].nunique()
  print(f"No. of unique data in '{column}' : {no_of_values} ")
  print (raw_data[column].unique())
  print('**'* 42)

No. of unique data in 'locality' : 1082
[1050 1880 4900 ... 1761 5576 3381]
************************************************************************************
No. of unique data in 'type_of_property' : 2
['house' 'apartment']
************************************************************************************
No. of unique data in 'subtype_of_property' : 24
['house' 'villa' 'exceptional property' 'farmhouse' 'apartment block'
 'town house' 'mixed use building' 'bungalow' 'manor house'
 'country cottage' 'mansion' 'castle' 'chalet' 'other property'
 'apartment' 'service flat' 'flat studio' 'ground floor' 'kot' 'penthouse'
 'duplex' 'loft' 'triplex' 'pavilion']
************************************************************************************
No. of unique data in 'price' : 4220
['340000' '525000' '550000' ... '487035' '455496' '451650']
************************************************************************************
No. of unique data in 'type_of_sale' : 1
['for sale']
************************************************************************************
No. of unique data in 'number_of_rooms' : 28
[  6.  11.   4.   5.   3.   1.   2.   8.  12.   7.  24.  20.  15.   0.
  19.   9.  10.  17.  18.  14.  16.  30.  22.  13.  nan 204.  33. 165.
  23.]
************************************************************************************
No. of unique data in 'house_area' : 693
['203' '250' '475' '325' '400' '220' '303' '442' '210' '273' '176' '200'
 '82' '350' '377' '291' '276' '110' '180' '260' '247' '115' '288' '185'
 '383' '522' '360' '124' '173' '130' '417' '470' '245' '761' '225' '305'
 'None' '277' '164' '120' '134' '289' '270' '50' '155' '249' '800' '230'
 '272' '170' '106' '217' '145' '146' '165' '160' '500' '166' '150' '343'
 '193' '215' '300' '90' '85' '100' '195' '122' '182' '330' '280' '279'
 '153' '140' '177' '239' '135' '700' '266' '144' '296' '380' '387' '99'
 '246' '204' '265' '207' '197' '236' '105' '184' '178' '449' '175' '190'
 '141' '320' '460' '240' '352' '183' '171' '136' '233' '255' '72' '385'
 '228' '186' '450' '212' '331' '254' '137' '95' '213' '152' '334' '91'
 '218' '192' '257' '104' '248' '222' '454' '364' '74' '138' '275' '206'
 '107' '227' '188' '354' '469' '224' '151' '205' '129' '980' '202' '163'
 '267' '310' '490' '216' '251' '516' '114' '214' '309' '172' '252' '201'
 '118' '131' '147' '132' '370' '302' '113' '444' '89' '159' '428' '86'
 '80' '112' '101' '315' '284' '187' '322' '318' '181' '189' '167' '88'
 '142' '396' '297' '660' '340' '55' '119' '103' '395' '232' '422' '264'
 '253' '117' '298' '108' '148' '440' '393' '221' '174' '96' '143' '109'
 '196' '361' '480' '785' '226' '930' '347' '345' '416' '234' '286' '327'
 '198' '274' '278' '287' '637' '375' '520' '515' '770' '335' '313' '290'
 '900' '123' '316' '127' '295' '616' '750' '329' '420' '336' '479' '292'
 '324' '179' '191' '461' '495' '355' '263' '312' '168' '435' '294' '431'
 '371' '382' '268' '235' '505' '321' '314' '363' '472' '775' '662' '333'
 '720' '394' '512' '149' '256' '157' '429' '154' '391' '412' '317' '430'
 '402' '208' '308' '392' '162' '457' '237' '630' '369' '158' '229' '600'
 '209' '339' '365' '341' '411' '582' '379' '337' '269' '319' '231' '262'
 '716' '211' '388' '445' '238' '326' '850' '356' '555' '597' '293' '487'
 '418' '1500' '743' '372' '285' '401' '466' '344' '405' '633' '349' '920'
 '311' '1100' '760' '399' '338' '511' '474' '725' '605' '580' '404' '489'
 '304' '481' '441' '465' '357' '242' '513' '282' '306' '397' '368' '403'
 '386' '373' '410' '281' '156' '439' '521' '261' '468' '259' '704' '485'
 '486' '75' '507' '342' '353' '686' '526' '407' '501' '241' '477' '271'
 '510' '219' '433' '244' '390' '427' '550' '348' '366' '572' '983' '456'
 '425' '581' '471' '328' '603' '1640' '504' '128' '415' '367' '419' '570'
 '672' '623' '722' '381' '615' '509' '374' '790' '301' '476' '754' '1454'
 '492' '426' '358' '1000' '484' '283' '571' '384' '710' '493' '199' '438'
 '459' '1200' '646' '549' '243' '494' '258' '351' '518' '499' '937' '362'
 '691' '446' '508' '640' '70' '409' '627' '648' '1461' '455' '575' '378'
 '496' '533' '78' '544' '169' '1019' '408' '609' '436' '423' '595' '554'
 '503' '612' '655' '565' '545' '307' '670' '406' '3560' '437' '908' '376'
 '651' '323' '560' '860' '578' '583' '491' '125' '524' '463' '502' '1407'
 '732' '685' '562' '610' '569' '424' '690' '594' '531' '706' '451' '528'
 '540' '912' '453' '530' '679' '584' '645' '601' '713' '607' '558' '346'
 '1107' '551' '223' '458' '538' '684' '1339' '523' '525' '519' '561' '482'
 '950' '835' '635' '1350' '483' '620' '332' '447' '604' '590' '434' '389'
 '613' '702' '735' '639' '828' '665' '678' '564' '574' '414' '650' '929'
 '546' '745' '543' '880' '666' '537' '552' '20' '47' '83' '31' '49' '42'
 '126' '62' '84' '81' '36' '28' '102' '45' '43' '25' '22' '29' '60' '40'
 '27' '65' '30' '24' '34' '33' '35' '21' '39' '68' '23' '48' '76' '77'
 '41' '18' '93' '38' '54' '26' '37' '46' '58' '52' '56' '67' '97' '44'
 '51' '63' '64' '66' '32' '111' '17' '98' '69' '53' '92' '71' '57' '59'
 '19' '14' '116' '94' '73' '61' '79' '16' '133' '87' '5' '139' '15' '121'
 '11' '31700' '730' '161' '13' '1' '194' '413' '680' '421' '478' '559'
 '588' '776' '915' '788' '1700' '1450' '585' '682' '2019' '577' '2400'
 '488' '840' '299' '2500' '542' '822' '677' '1190' '774' '1013' '647'
 '464' '858' '797' '748' '736' '1070' '535' '566' '498' '2562' '462'
 '1095' '619' '1121' '529' '1900' '1525' '975' '527' '473' '576' '398'
 '675' '780' '448' '618' '1050' '718' '641' '467' '865' '452' '432' '1254'
 '1250' '1007']
************************************************************************************
No. of unique data in 'fully_equipped_kitchen' : 2
[1 0]
************************************************************************************
No. of unique data in 'furnished' : 1
['None']
************************************************************************************
No. of unique data in 'open_fire' : 2
[0 1]
************************************************************************************
No. of unique data in 'terrace' : 2
[1 0]
************************************************************************************
No. of unique data in 'terrace_area' : 185
['None' '40' '125' '80' '30' '17' '60' '68' '20' '6' '10' '15' '32' '25'
 '24' '28' '100' '13' '12' '4' '16' '50' '8' '21' '52' '33' '111' '22'
 '34' '36' '45' '23' '63' '18' '5' '120' '144' '27' '70' '35' '49' '57'
 '26' '14' '55' '90' '9' '47' '61' '11' '83' '138' '58' '19' '250' '82'
 '59' '127' '42' '38' '41' '66' '94' '150' '230' '75' '29' '71' '300' '48'
 '7' '110' '85' '3' '31' '88' '54' '96' '46' '170' '200' '43' '86' '160'
 '74' '2' '65' '708' '95' '105' '51' '115' '123' '196' '62' '56' '37' '73'
 '147' '77' '92' '72' '145' '69' '220' '98' '112' '78' '64' '108' '500'
 '161' '44' '157' '81' '350' '290' '122' '1' '76' '39' '130' '53' '1020'
 '1150' '67' '87' '117' '761' '84' '135' '136' '180' '175' '600' '79'
 '158' '156' '137' '140' '306' '93' '210' '242' '217' '104' '225' '141'
 '102' '114' '124' '184' '133' '101' '106' '224' '99' '400' '167' '165'
 '176' '143' '162' '330' '116' '126' '174' '179' '159' '142' '97' '584'
 '149' '118' '369' '371' '109' '163' '494' '187' '185' '265' '270' '418'
 '495']
************************************************************************************
No. of unique data in 'garden' : 2
[0 1]
************************************************************************************
No. of unique data in 'garden_area' : 1192
['None' '430' '1400' ... '1889' '1095' '966']
************************************************************************************
No. of unique data in 'surface_of_the_land' : 3278
[  95.  826. 1543. ... 3459. 3569. 3939.]
************************************************************************************
No. of unique data in 'surface_of_the_plot_of_land' : 1
['None']
************************************************************************************
No. of unique data in 'number_of_facades' : 5
['2' '4' '3' 'None' '1']
************************************************************************************
No. of unique data in 'swimming_pool' : 2
[0 1]
************************************************************************************
No. of unique data in 'state_of_the_building' : 7
['to be done up' 'as new' 'good' 'to renovate' 'None' 'just renovated'
 'to restore']
************************************************************************************
No. of unique data in 'construction_year' : 220
['1901' '1992' '1853' '1918' '1977' '1990' '1996' '1952' '1999' '2020'
 '1945' '1998' '1972' '1994' '1969' '2001' 'None' '2004' '1955' '1937'
 '1874' '1965' '1960' '1875' '1850' '1959' '1950' '1926' '1936' '1980'
 '1974' '2010' '1968' '2000' '1989' '2013' '2019' '2017' '1780' '1942'
 '2003' '1953' '2012' '2007' '1951' '2005' '1914' '1987' '1973' '1925'
 '1930' '1905' '1978' '1976' '1964' '1970' '2018' '1963' '1939' '1962'
 '1854' '1906' '1985' '2006' '1983' '2015' '1975' '1946' '1900' '1831'
 '1903' '2002' '1923' '1920' '1984' '2016' '1910' '2009' '1947' '1940'
 '1956' '1993' '1979' '1991' '1971' '1961' '2021' '1995' '1908' '1957'
 '1931' '1899' '1941' '1988' '1949' '1938' '1986' '1954' '1997' '1958'
 '1967' '1981' '1935' '1934' '1933' '1919' '2008' '1966' '1880' '2011'
 '1982' '1928' '1932' '1924' '1948' '2014' '1869' '1763' '1916' '1896'
 '1912' '1891' '1922' '1842' '1870' '1815' '1895' '1943' '1889' '1929'
 '1840' '1770' '1898' '1890' '1776' '1902' '1888' '1892' '1760' '1867'
 '1907' '1800' '1830' '1802' '1860' '1927' '1855' '1885' '1913' '1904'
 '1911' '1864' '1897' '1762' '1755' '1798' '1868' '1858' '1841' '1759'
 '1873' '1820' '1872' '1817' '1915' '1921' '1814' '1781' '1883' '1769'
 '1775' '1944' '1881' '1894' '1852' '1790' '1782' '1835' '1917' '1825'
 '2022' '2048' '1878' '1909' '2023' '1829' '1844' '1879' '1863' '1768'
 '1809' '1784' '1777' '1887' '1865' '1876' '1849' '1813' '1834' '1861'
 '1857' '1772' '1793' '1786' '1862' '1886' '1871' '1836' '1801' '1893'
 '1796' '1826' '1792' '1877' '1787' '1803' '1789' '1822' '1795' '1791']
************************************************************************************

## Drop duplicates row , missing values & rename columns

In [10]:
# Drop the duplicated rows
raw_data.drop_duplicates(inplace=True)

In [11]:
# rename columns name 'locality' to 'postal_code'

raw_data.rename(columns={'locality' :'postal_code'},inplace=True)

In [12]:
# Drop columns with only 1 unique value

raw_data.drop(columns=['type_of_sale','furnished','surface_of_the_plot_of_land'],inplace=True)

In [13]:
raw_data.isna().sum()

postal_code                   0
type_of_property              0
subtype_of_property           0
price                         0
number_of_rooms               2
house_area                    0
fully_equipped_kitchen        0
open_fire                     0
terrace                       0
terrace_area                  0
garden                        0
garden_area                   0
surface_of_the_land       21840
number_of_facades             0
swimming_pool                 0
state_of_the_building         0
construction_year             0
dtype: int64

In [14]:
# fill missing value as "None" for columns: surface_of_the_land
raw_data.surface_of_the_land = raw_data.surface_of_the_land.fillna('None')

In [15]:
# drop 2 rows of missing value for columns: number_of_rooms)

raw_data.dropna(inplace=True)

In [16]:
# Remove the 'None' (str) entries
raw_data = raw_data[(raw_data['house_area'] != 'None')]

# Convert the type to int
raw_data['house_area'] = raw_data['house_area'].astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [17]:
raw_data.isna().sum()

postal_code               0
type_of_property          0
subtype_of_property       0
price                     0
number_of_rooms           0
house_area                0
fully_equipped_kitchen    0
open_fire                 0
terrace                   0
terrace_area              0
garden                    0
garden_area               0
surface_of_the_land       0
number_of_facades         0
swimming_pool             0
state_of_the_building     0
construction_year         0
dtype: int64

## label encoding

In [18]:
# labet encoding for "type_of_property"
# Change house to 0, and apartment to 1

raw_data['type_of_property'] = raw_data['type_of_property'].replace({"house":0 ,"apartment":1})

In [19]:
for item in raw_data['price'].unique():
  print (item)

340000
525000
550000
535000
385000
549000
519000
545000
105000
520000
250000
85000
515000
150000
140000
20000
539000
540000
60000
15000
530000
93000
529000
120000
180000
129250
25000
35000
508800
65000
160000
50000
310000
37500
215000
38000
40000
114000
225000
100000
10000
75000
135000
no price
524000
240000
110000
200000
125000
220000
95000
521000
99000
548000
30000
39000
175000
517000
190000
285000
325000
34235
546600
158000
509000
115000
523300
535530
130000
537500
80000
170000
290000
77000
49000
55000
165000
149000
205000
300000
90000
145000
435000
255000
67500
169000
87000
535500
259000
523000
45000
509200
538000
78500
210000
112000
70000
543869
544416
124000
528600
167000
295000
508000
505000
536000
537000
524999
547000
19000
510000
540111
534000
539900
549500
518500
547500
28500
24000
528000
512500
549999
531000
502300
511600
12500
27000
513000
475000
538500
69900
549935
545500
518056
599000
555000
560000
598000
595000
590000
579000
593000
559000
570000
575000
597000
600000
580000
569000
589000
568000
578000
585000
574000
565000
579500
587000
595500
576000
584000
596000
589600
572500
582400
588000
554500
560255
560256
599900
559500
571000
591000
597500
574500
567000
564000
589200
582000
574999
595777
650000
625000
649000
649900
610000
634000
620000
645000
629000
635000
630000
605000
627000
640000
629900
615000
614000
610300
633000
618000
619000
642000
648000
632000
618700
629500
638000
639000
637500
624900
624000
609000
637444
647000
623900
670000
685000
699000
695000
668000
659000
690000
675000
680000
660000
665000
698000
700000
689000
679000
696000
669000
655000
671000
688000
693000
659500
678000
697000
652000
692000
695900
658000
699500
673000
667500
687000
699900
666000
674000
694000
750000
745000
725000
749000
720000
729000
735000
715000
739000
730000
737500
740000
719000
710000
734000
748000
709000
795000
732600
739500
724000
722000
749800
738000
748500
728000
799000
790000
775000
760000
780000
755000
769000
798000
785000
765000
770000
777000
789000
779000
800000
759000
778000
774000
794600
788000
765822
759040
850000
835000
825000
845000
849000
829000
840000
810000
820000
837000
819000
830000
839000
824000
842000
818000
815000
805000
847000
840400
840900
845500
811000
895000
899500
855000
875000
900000
880000
870000
890000
899000
888000
864000
885000
869000
860000
865000
859500
889000
865700
875920
879000
897000
899999
881000
879500
898000
925000
950000
920000
940000
945000
935000
928000
949000
915000
907500
947000
919900
939000
948000
930000
911000
910000
49500
2500
14500
28000
8160
6600
89000
87500
94950
98000
59500
94000
79500
63000
91000
58000
69000
99500
99900
97000
99999
89900
92000
79000
72000
67000
73000
72500
69500
64500
82500
83000
83500
97500
84500
89500
62000
54000
89999
88000
77500
61000
76000
78000
92500
57000
74000
94500
64000
64840
68000
82100
84000
95500
84900
61500
63500
127500
137000
139000
129000
132000
107000
139500
144500
119000
142000
132500
109000
149500
128000
138000
144000
149900
109500
134000
139800
104000
142500
123500
109700
146000
129990
141000
122000
139900
127000
148000
137500
103000
143000
147500
147000
148500
114700
139250
118000
124500
138800
102500
144813
119500
123000
136700
108900
111500
135200
133000
104990
134500
117000
129500
119999
146500
113000
116000
142938
109900
108000
136000
121000
147905
149935
126000
106000
129600
129900
119900
107500
122500
134950
100298
124950
131500
104500
124999
125500
145900
149950
142700
115700
149995
133100
133500
149999
134900
135300
138500
139780
148430
102000
120900
117500
148800
149700
185000
195000
199000
169500
198000
179000
155000
154900
192000
184500
187500
159000
159500
172000
179500
199900
179900
173000
198800
154000
167500
189000
174000
186000
199500
162500
178000
157000
164500
177500
179999
189500
189900
197000
188000
151000
162000
199950
193000
183200
198500
164000
168500
171000
152000
163000
181500
164483
168700
197900
166000
168000
193500
166350
177000
194000
191362
167560
192579
192635
178500
183500
186500
191500
160350
183029
174900
193107
194500
156000
188979
154500
199860
172500
175500
169900
172900
165449
153000
184000
188384
192244
190901
176499
165500
181000
194050
177212
155889
199800
199863
175455
182000
164589
167184
167408
171759
187000
198059
197500
198650
192882
198200
191400
196749
185500
176385
192200
180563
155500
167572
194954
169250
180900
164995
192500
176700
192700
198900
152500
176000
199420
182900
174915
180250
184900
196793
197893
171360
196000
197300
179904
157500
195727
183000
182500
174440
190600
180500
184800
159624
195888
163200
161000
194400
180750
179191
189050
192250
194860
176750
163750
196950
198470
193510
190300
194800
197041
159900
153702
189113
199990
173259
178200
182130
192875
173650
158959
199775
174500
195800
196500
199400
169950
189750
196180
171895
163653
183080
187657
170500
173269
194900
171500
183838
199999
186860
185900
174493
196840
158700
182564
196945
183084
170563
194784
169999
163350
164900
170300
197200
191000
165900
181600
158500
154950
176500
195285
187875
177900
163500
173500
167943
195900
185950
179750
186427
192400
198750
152977
172999
180999
181616
189999
198191
199464
199750
179950
160370
163508
173358
180127
183383
195871
178908
199717
194285
195990
197395
159800
174685
199700
176900
182750
184822
161600
187662
189200
184999
191361
199430
151500
163700
192028
182774
165503
166500
169750
186900
165807
168524
174118
180209
183474
190128
195870
198202
189743
160500
176250
182610
199479
192630
196798
159750
174100
160371
160372
164746
167050
169550
175540
194475
195566
168400
172100
173100
180200
180300
186200
186300
190200
193100
193800
191700
172490
152300
197987
164050
156700
196400
171948
177732
182565
192275
199301
195500
174600
180950
160842
163925
197777
161157
190700
165200
186400
197380
199995
198300
161500
245000
208000
249999
235000
249000
239000
230000
219000
203000
237000
221000
228000
229000
234000
248000
249950
209000
249500
219418
209500
232500
238500
244000
239500
238918
229500
244500
224000
238000
245500
243000
227000
204000
247000
212500
208500
218400
219750
226000
243260
242500
223000
242176
220500
202000
234320
217500
205500
210940
242300
245395
229900
216000
227500
229785
241500
249053
218754
233000
213500
221113
223875
206000
212400
219500
222000
248800
207000
202500
207500
217000
222500
202192
206324
206421
230390
214500
245870
232000
218500
224500
236000
247500
231500
243225
221500
227392
235679
236570
243696
246069
241000
215500
219900
222727
234500
210500
242000
207397
245197
214900
224900
239675
214950
213000
246000
212000
218000
232311
206500
214000
228009
245900
248095
213300
201500
223500
248500
237500
225500
236250
214800
226161
231364
232900
212017
206432
212607
231750
249600
207656
241100
241578
244900
234800
202905
231970
223786
211000
212478
238941
200235
230736
209600
219200
244950
240122
207600
213180
207010
200704
208039
217905
203600
232400
249700
204500
244600
240500
201298
233795
233853
234723
234908
235653
236108
236350
236405
242993
237315
239235
239618
249565
202040
246315
233500
239900
210871
218280
208100
238300
228500
214250
225380
236315
243750
223380
231000
223850
205030
221108
249900
235777
236500
248650
238750
203500
235500
203850
249850
201112
216500
208900
207535
235900
242900
240750
245634
208560
239200
202270
242890
225078
225350
215100
248900
223946
238650
207775
226578
223483
203080
222390
207170
211500
233615
247495
229260
216800
218800
219800
223400
234900
232250
224950
228389
242207
227550
242600
207539
223064
234600
209800
227950
206101
206200
208142
225250
224299
223885
204877
207571
240350
248063
216215
217017
236688
224300
249415
243333
247335
204783
241700
243342
240183
238400
240900
204472
241588
225450
222285
224479
210749
249298
228750
235450
249167
218090
225225
229213
204860
208470
209420
211270
212270
237040
238800
233800
212415
213115
238405
209900
239400
239999
242497
219700
219100
242826
249800
206035
226500
229300
248580
231115
210317
214639
239154
244800
217624
219749
223138
202950
220448
235750
239800
235600
235100
223750
215270
219250
231450
241619
207034
236066
214100
246611
211999
231981
231035
239350
244350
246250
236430
229400
206683
209566
210620
214633
227800
237800
247333
208300
218427
204573
210939
216320
217120
230155
231503
241600
200160
207570
209605
209760
214080
215710
222560
226720
234628
242144
215900
233900
243900
235813
244125
241167
220675
224278
238700
206900
212573
224460
238066
247900
205261
217900
221540
240356
240558
233750
201402
202700
228284
230500
236700
200348
220795
227942
236800
246750
210700
226250
220300
221400
221600
232100
233200
233600
235800
237100
243300
224308
228268
205820
241283
216396
246155
231413
246012
223900
209750
227200
231456
232303
246995
247100
247195
215382
214990
220386
226557
204790
205900
248848
200500
202840
236814
206307
220900
245750
215215
212200
215300
201000
201130
212475
214050
214975
218030
219025
219050
221140
224025
228670
233136
233175
234175
234825
236950
245690
249200
209627
244870
249375
249376
235200
242800
241120
248090
203583
209063
217571
218493
218700
243500
211808
216998
217369
217487
219396
222931
227460
228804
233836
238482
239560
243631
208150
213987
239056
239300
231600
244200
200250
247950
200280
205280
220590
220630
223720
237600
239117
239950
242213
240250
242518
248300
215938
239990
242560
242950
243950
246340
248920
231899
220750
217400
235682
213650
234950
214400
220850
218734
220160
222718
225904
227359
230852
232593
247200
232800
245700
249430
206570
215750
226700
209183
221550
246500
229800
248700
280000
282500
265000
275000
279000
299900
270000
260000
298000
299500
299999
269000
267000
287000
298500
268000
289000
299000
283000
256000
258000
262000
277600
284000
288000
293000
297000
289500
250314
273000
274000
283500
254500
261000
264000
272500
274500
279500
284500
296500
287500
269500
277418
252000
291000
288500
263000
278000
252200
281000
269255
299615
259500
276000
290500
292000
277500
291500
262500
269900
254300
284415
273970
282353
292500
272000
264900
267700
257000
296000
251000
253000
276500
277750
269800
261745
292995
294500
273132
274382
297400
264500
253500
265500
272912
286000
290836
257500
297900
290833
259700
279900
285400
289900
294000
282000
262800
296400
286500
259900
275750
277900
280875
254000
275100
250692
253720
277890
253900
264075
271500
299700
268652
276115
297382
250540
270959
280500
258500
263500
278800
297500
255300
281400
263120
279676
286840
290925
289850
252880
255408
261443
285500
293100
256047
286136
295600
286495
259250
287300
299950
250700
255581
251851
257380
259800
269750
290416
299750
260255
274984
277000
284800
269400
271000
252506
255450
267500
275500
278500
251500
282781
256125
285100
290100
292585
258125
283750
298750
293500
268500
273500
294750
296900
293600
260500
261250
281500
284900
296250
285870
276400
257650
254900
265900
278038
275226
255560
297275
269610
275808
272850
283618
253725
267450
257800
267520
298650
288275
264583
283650
256800
282665
292119
297343
259854
286750
256500
282160
277771
278600
269790
280712
264624
275080
281223
266500
295438
275622
297757
252500
265617
266117
267402
273902
295200
293015
291750
277292
290061
274900
256878
252400
292106
296992
263659
268950
290415
294215
297405
253400
280530
267301
281808
267206
264473
276307
280417
289356
295534
286200
284350
290400
254006
258088
252986
276200
261450
276230
261600
263800
261500
299250
258600
259200
260800
273861
259968
269950
253200
275688
257169
264360
251400
263897
280841
266000
293529
295680
252750
288016
258987
267373
279430
295500
299810
277200
255675
272482
274700
280600
283250
298942
265200
272450
278548
260762
270555
288953
291321
262350
250275
262025
264975
254140
256255
285024
254700
255486
259433
268706
270890
277700
257538
272950
274496
284638
282322
265400
267950
288700
258700
265300
275200
267093
288762
291354
291603
299014
299990
279110
256454
294885
250874
270900
289800
252900
273300
256372
259875
263990
269144
275832
281293
291033
295668
282900
250354
250564
258519
272202
289288
287240
293690
294550
257342
251600
286802
250500
266200
264026
291243
298893
259575
272600
286203
292082
259300
278434
283846
264950
253177
271304
298800
251250
251700
260750
269100
269680
250433
258909
271430
251200
252600
255100
255500
256100
267400
270500
277100
278900
295300
255192
268300
269325
274040
274825
278400
280710
282950
291950
295660
296625
279246
284722
287189
289582
253995
265020
299240
251677
252550
263868
269804
276533
284963
287091
291955
259100
263277
273020
254200
262300
292100
250900
273414
299213
269568
288540
251080
257250
270820
274050
288550
251430
277274
296300
258210
282250
288798
260700
267800
270800
271400
287970
254541
298275
280439
291352
260537
288400
288450
291100
294578
257676
271300
250250
256860
320000
315000
319000
335000
335500
302500
350000
329000
312000
316000
338000
339750
305000
330000
339000
345000
328000
329500
343000
349000
303600
307000
311000
317000
317200
321000
323000
327000
327500
332000
334000
337000
342000
314000
307500
309000
339500
349500
338500
302000
321640
332956
341000
309500
308000
336605
329250
346000
318000
325723
332711
348000
303500
305640
330196
341467
348263
329950
327600
349442
303168
308400
326500
319900
324000
306925
324996
334200
333000
335724
306500
330615
336000
304500
325360
330982
328800
346725
306000
336250
320668
336500
326000
304950
312500
326625
321580
334048
301000
346453
347000
301300
314900
327185
343900
314800
335046
335900
347540
326750
308750
309900
304000
309640
344500
316900
319500
320500
324900
346500
329900
331000
311200
316575
336520
341700
343295
315777
344410
322000
334310
349800
303900
305500
318900
328500
339900
332500
331500
336700
314957
343500
340500
310500
318500
319800
302950
322200
322167
318275
308500
322500
319450
317500
324210
324700
316766
316700
309935
348500
311450
301501
314178
338900
325900
345900
349995
307900
309442
322800
314500
313400
301422
329600
324500
311817
306250
315500
313000
304328
331600
303000
348750
310485
311175
306899
325100
326700
302075
307475
320025
332575
338400
319700
301500
328323
304900
318110
347371
330448
316500
302900
312363
305740
301933
313233
332090
333425
345500
317850
325270
337633
311560
312350
327900
331425
325384
313647
316393
349950
320919
322921
301627
318270
332527
300794
317866
330239
305837
314979
347396
347400
322335
338550
306400
330900
337146
337150
343069
324783
318600
309950
314060
333500
327984
319646
310300
344250
333569
343549
336820
308546
316050
331200
335280
311240
334500
337700
336797
316260
348260
338017
300389
319714
335490
303538
349900
335090
380000
358000
365000
398500
399000
395000
375000
360000
355000
359000
370000
354960
378420
369000
379000
390000
367200
389000
368000
371280
351000
352000
395200
400000
357000
354500
379500
384500
399500
359040
387600
397500
382000
352500
396700
354000
372059
353800
361000
369500
374500
374000
398000
358300
368989
375280
382346
375101
364000
363000
387346
373792
392500
367500
366000
357500
359500
372000
378000
381000
397000
387000
367000
371850
399550
371838
380245
354974
360800
351750
357377
377000
389900
355200
361800
372500
378500
398900
372464
367709
353500
371000
391000
396500
388750
389850
377500
363591
380056
356500
386500
381670
374900
394000
372519
359900
365683
380500
399600
364500
355217
383770
389500
350500
383000
383500
355691
382688
397700
367512
393000
355750
353000
398250
362000
361480
384000
358102
353875
399999
375700
399750
393500
352100
372099
365500
357360
391410
394107
358720
383740
396000
360500
388000
350010
384450
399900
369250
381250
370941
391400
359450
354750
391469
373040
399525
376000
385600
394800
363991
376200
351399
364397
366200
357200
356000
357510
376368
366371
350115
382325
412500
450000
425000
419000
410000
430000
449000
445000
442525
440000
415000
427500
420000
418000
446000
439000
447500
409500
414000
404000
418250
428250
438000
448000
429000
433000
417500
448950
428000
403000
405000
432000
444500
441000
402000
419950
459000
407950
409000
417000
421000
441332
427000
422100
434000
427125
401648
404635
422627
427883
436500
417015
416000
443000
439500
442000
447000
449500
404900
437175
422000
400500
408000
431700
410500
424500
424000
429800
438950
441200
420666
440500
437500
401500
407185
431450
407000
449900
437503
408250
401933
411595
423594
426136
430808
412886
441656
431000
444000
411000
449990
434134
408500
426200
423500
435500
414900
417680
437780
407500
414480
444730
402412
406535
436000
411655
440075
410850
435750
431299
433750
405766
406010
423850
411480
423100
411650
418600
499000
495000
498000
485000
455000
458000
465000
464500
476000
479000
460000
470000
480000
490000
479900
495720
464000
468000
489000
478000
497500
488000
487760
490031
499999
500000
464475
469000
469500
459667
473000
451000
469400
472350
487425
497475
482400
455092
486000
450255
455400
458450
459800
460650
463170
465650
468150
470650
499500
466099
467524
452500
457000
462300
455696
452000
493915
492450
489750
463000
474500
456000
475410
489250
460540
487000
494350
470400
482500
497000
453250
497806
488063
486500
454000
471900
469636
461400
494720
490350
471461
456944
463015
478058
486820
493340
469700
452350
484150
492500
501500
524500
541000
514080
526000
546861
506500
543000
544000
506000
520200
517575
515500
520500
502500
528500
540500
514000
509275
544500
525304
549900
525190
542000
507800
524192
528765
509250
519750
585500
561700
566000
594500
598500
551190
579900
584750
557000
583000
574524
561279
577000
599174
568500
587814
586395
579624
552120
554000
561000
556000
602000
632500
617500
609500
642309
628000
628336
621000
620200
634500
604000
606500
622000
637000
602309
612500
603100
636000
616160
657000
656000
683000
695825
693450
650500
699400
696500
667000
686000
684000
674500
749500
705000
701000
743000
724995
749350
784500
754500
774500
768000
799500
849500
848000
807500
878000
892000
854887
879800
897900
868000
893150
936000
904500
29900
49900
48000
39999
42000
42500
47500
48500
19900
9999
11825
79900
88500
98500
59900
73500
56000
69999
82000
96000
59000
58500
74900
53000
74500
93500
58950
64900
66105
81000
86000
68500
52000
97410
73900
76500
56050
62500
52500
96500
144900
124900
129800
128500
116500
113500
112500
134700
118900
116050
139999
109450
109990
103306
126057
114900
101900
120750
139432
137900
118500
113435
121750
136615
136900
198174
178800
159999
189650
178450
150349
153995
174950
182548
199244
164750
194628
173740
194940
196020
174999
156250
156500
166990
155900
152600
167950
192664
176080
230957
220790
234260
224980
225400
219950
230819
249695
221342
237908
241908
249759
231840
225600
246125
218300
218602
235365
221051
221938
204740
246249
233078
237670
241267
239850
237652
248999
224289
208640
199635
234700
249635
246100
246700
221495
223450
216250
220229
241651
248630
243600
244400
245365
236163
215329
228300
246796
210770
230133
233857
236140
237020
249490
249830
244744
243010
206451
207736
231168
233152
230672
212703
213422
225527
236214
237095
224750
233490
208291
231430
222981
243550
233675
236750
214600
239225
249755
229738
217291
240400
240512
202736
222222
242400
208735
232821
237047
246877
237728
211744
216823
221950
227375
248990
222692
299483
277275
298400
281461
283931
269494
278264
284950
265600
277793
285757
297029
267013
294983
255811
268295
282650
284025
287982
292383
297306
299344
251495
275405
283979
296694
298375
250600
288701
268200
294900
277350
252716
266702
288417
274975
298923
269975
276361
257839
273900
288900
278575
280350
286461
296025
270575
271225
271700
263150
268350
269700
299243
266400
285800
273060
262976
281920
289994
265137
269326
287280
299100
299667
299992
299960
256722
258222
288493
279775
280150
279666
290710
292475
292148
288860
250255
263375
259650
297750
259950
290240
279950
256200
258025
265976
279400
291925
298320
266461
274286
278333
280993
299671
293550
299530
274800
257375
287600
276900
298875
292450
296735
299760
261900
267435
299467
279850
277780
289125
262270
287630
261415
274716
286300
253300
256250
274950
279650
257600
280700
298600
254100
268900
262900
299510
274370
260400
282293
298068
278668

## Data formation

In [20]:

# Convert the price to int
# some data in price column contains as 'no price'
# so we filter out that string:


raw_data['price'] = raw_data[raw_data.price != "no price"]['price']
raw_data.dropna(inplace=True)
raw_data['price'] = raw_data['price'].astype(int)

## Remove outlier

In [21]:
# In column "number_of_rooms" so many invalid data

raw_data.number_of_rooms.max()

204.0

In [22]:
# max room number should be : 20
raw_data = raw_data[(raw_data['number_of_rooms'] < 20) & (raw_data['number_of_rooms'] > 0)]

# Convert to int
raw_data['number_of_rooms'] = raw_data['number_of_rooms'].astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

## Droping columns

In [23]:
raw_data['terrace_area'].value_counts()
# (25 000) entries are None in "terrace_area"
# the columns will be dropped

raw_data.drop(columns=['terrace_area'],inplace=True)

In [24]:
# Drop the columns 'subtype_of_property'
del raw_data['subtype_of_property']

In [25]:
raw_data.garden_area.value_counts() 

# 33 000 'None' entries in 'garden_area'

raw_data.drop(columns=['garden_area'],inplace=True)

In [26]:
raw_data.construction_year.value_counts(normalize=True)
# 38% of data construction year unknown.
# drop construction year column

raw_data.drop(columns=['construction_year'],inplace=True)

## Missing values / Null values handling

In [27]:
# Surface of the land has 19000 None entries
raw_data.surface_of_the_land.value_counts()
# Replace 'None' by 0
raw_data['surface_of_the_land'] = raw_data['surface_of_the_land'].replace({"None":0}).astype(int)

In [28]:
# Number of facades has a lot of None value
raw_data.number_of_facades.value_counts()

# Replace 'None' by 0
raw_data['number_of_facades'] = raw_data['number_of_facades'].replace({"None": 0}).astype(int)

# Drop the 1-facade houses.
# raw_data = raw_data[(raw_data['number_of_facades'] != 1)]
raw_data = raw_data.loc[(raw_data['number_of_facades'] != 1)]

In [29]:
# State of the building data has 'None'
raw_data.state_of_the_building.value_counts()

# Replace 'None' by 'unknown'
raw_data['state_of_the_building'] = raw_data['state_of_the_building'].replace({"None": "unknown"})
raw_data.state_of_the_building.value_counts()

as new            12188
good              11225
unknown            9979
to be done up      2891
to renovate        2507
just renovated     2184
to restore          149
Name: state_of_the_building, dtype: int64

## Export cleaned data

In [30]:
raw_data.dropna(inplace=True)
raw_data.reset_index(drop=True, inplace=True)
raw_data.shape

raw_data.to_csv('cleaned_apartment.csv')

In [31]:
raw_data

,postal_code,type_of_property,price,number_of_rooms,house_area,fully_equipped_kitchen,open_fire,terrace,garden,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building
0,1050,0,340000,6,203,1,0,1,0,95,2,0,to be done up
1,1880,0,525000,6,250,1,0,1,1,826,4,0,as new
2,4900,0,550000,11,475,1,0,1,1,1543,4,0,good
3,7912,0,550000,4,325,1,0,1,1,3570,4,0,good
4,6032,0,550000,5,400,1,0,1,1,616,3,0,as new
...,...,...,...,...,...,...,...,...,...,...,...,...,...
41118,2310,0,468000,3,180,1,0,0,0,0,4,0,unknown
41119,1800,0,454993,3,169,0,0,0,0,389,3,0,unknown
41120,3530,0,475000,3,222,0,0,0,0,1124,4,0,unknown
41121,6700,0,475000,9,240,0,0,0,0,200,2,0,unknown
41122,2018,0,488000,3,145,0,0,0,1,0,3,0,unknown